---
- name: Configure inventory
  hosts: all
  gather_facts: no
  roles:
    - common/config-inventory

- name: Rolling upgrade of all controllers to RHEL 7.4 and latest OVS
  hosts: overcloud-controllers
  serial: 1
  become: true
  tags: minor_update_controllers
  roles:
    - common/controller/disable
    - common/node/update
    - common/controller/enable

- name: Rolling upgrade of all computes to RHEL 7.4 and latest OVS
  hosts: overcloud-computes
  serial: 1
  become: true
  tags: minor_update_computes
  roles:
    - common/node/update

- name: Move the cluster into maintenance mode and stop all OpenStack services
  hosts: overcloud-controllers
  become: true
  roles:
    - common/controller/stop

- name: Upgrade controller0 to ocata, pike, master and then start all OpenStack services
  hosts: overcloud-controllers[0]
  become: true
  roles:
    - ocata/controller/upgrade
    - pike/controller/upgrade
    - master/controller/upgrade
    - common/controller/start
