- name: Check for shade virtualenv
  stat: path={{ shade_virtualenv_path }}
  register: shade_venv

- name: Create shade virtualenv
  pip:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    virtualenv: "{{ path_venv }}"
    virtualenv_site_packages: yes
  with_dict:
    setuptools: "17.0"
    pytz: "2016.4"
    shade: "1.22.2"
    pip: "8.1"
  vars:
    path_venv: '{{ shade_virtualenv_path }}'
  when: shade_venv.stat.exists == False

- name: Use shade virtualenv
  set_fact:
    ansible_python_interpreter: "{{ shade_virtualenv_path }}/bin/python"
