- name: Source overcloudrc file
  vars:
  shell: |
    source ~/overcloudrc
    echo "
    auth_url: $OS_AUTH_URL
    username: $OS_USERNAME
    password: $OS_PASSWORD
    project_name: $OS_TENANT_NAME
    "
  register: creds
