# FIXME: single shot systemctl call?
- name: Stop all OpenStack services on {{ inventory_hostname }}.
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ controller_openstack_services }}"
